language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build

cache:
  directories:
    - $HOME/.gradle
