language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra

before_install:
  - mkdir -p "$ANDROID_SDK/licenses"
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_SDK/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_SDK/licenses/android-sdk-preview-license"

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build

cache:
  directories:
    - $HOME/.gradle
